name: tracking_wo_BnW
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py36_0
  - cffi=1.10.0=py36_0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cycler=0.10.0=py36_0
  - cython=0.29.2=py36he6710b0_0
  - dbus=1.13.2=hc3f9b76_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=2.1.2=py36h0e671d2_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=he6710b0_1
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - olefile=0.46=py36_0
  - openssl=1.0.2p=h14c3975_0
  - pcre=8.42=h439df22_0
  - pillow=5.1.0=py36h3deb7b8_0
  - pip=18.1=py36_0
  - pycparser=2.19=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.6.0=py36h22d08a2_6
  - python=3.6.4=hc3d631a_1
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - qt=5.6.2=hd25b39d_14
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - setuptools=40.6.3=py36_0
  - sip=4.18.1=py36hf484d3e_2
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pytorch=0.3.1=py36_cuda8.0.61_cudnn7.0.5_2
  - torchvision=0.2.0=py36h17b6947_1
prefix: /usr/stud/bergmanp/anaconda3/envs/tracking_wo_BnW

